
server:
  port: 8081
spring:
    application:
      name: user
    datasource:
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
    jpa:
      hibernate:
        ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG


