services:
  person-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - person_data:/var/lib/postgresql/data
    networks:
      - checkoutsy-network

volumes:
  person_data:

networks:
  checkoutsy-network:
    external: true
