services:
  person-db:
    image: person-db:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: person-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - person_data:/var/lib/postgresql/data
    networks:
      - checkoutsy-network

volumes:
  person_data:

networks:
  checkoutsy-network:
    external: true
